### ISSUE TITLE
Funciona com o dispositivo Sunmi K2?

### ISSUE THREAD

**Issue by davimateus1** [linvix-sistemas/react-native-tectoysunmisdk#1]
Estou com um dispositivo desses no trabalho e preciso fazer a conexão, só consegui com react-native-print e infelizmente não foi bem aceito pelos superiores, essa biblioteca consegue realizar a impressão com o dispositivo K2? Já tentei muitas coisas e infelizmente não consigo, se essa biblioteca não resolver também aceito ideias de como posso fazer, passos a passos e etc. Muito obrigado!

**Comment by cristiano-linvix** [comment]
Boa tarde @davimateus1, não estou recebendo notificações das issues, desculpe a demora.

Sim essa biblioteca imprime no K2 e K2 Mini.
